# -*- coding: utf-8 -*-
"""numpy exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ov9_54axqoMiNIUIIxS5gfdjE_bTqH4n

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np
"""

import numpy as np

"""#### Create an array of 10 zeros"""

arr = np.zeroes(10)
print(arr)

"""#### Create an array of 10 ones"""

arr=np.ones(10)
print(arr)

"""#### Create an array of 10 fives"""

arr=np.full(10,5)
print(arr)

"""#### Create an array of the integers from 10 to 50"""

arr=np.arange(10,51)
print(arr)

"""#### Create an array of all the even integers from 10 to 50"""

arr=np.arange(10,51,2)
print(arr)

"""#### Create a 3x3 matrix with values ranging from 0 to 8"""

arr=np.arange(9)
array=arr.reshape((3,3))
print(array)

"""#### Create a 3x3 identity matrix"""

arr=np.eye(3)
print(arr)

"""#### Use NumPy to generate a random number between 0 and 1"""

arr=np.random.rand()
print(arr)

"""#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution"""

arr=np.random.normal(size=25)
print(arr)

"""#### Create the following matrix:"""

arr=np.arange(0.01,1.01,0.01)
array=arr.reshape(10,10)
print(array)

"""#### Create an array of 20 linearly spaced points between 0 and 1:"""

import numpy as np
arr=np.linspace(0,1,20)
print(arr)

"""## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
"""

arr=np.arange(1,26,1)
array=arr.reshape(5,5)
print(array)

import numpy as np
arr=np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
print(arr)

arr=np.array([[20]])

import numpy as np
arr=np.array([[2],[7],[12]])
print(arr)

arr=np.arange(21,26)
print(arr)

arr=np.arange(16,26)
array=arr.reshape(2,5)
print(array)

"""### Now do the following

mat = array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat
"""



"""#### Get the standard deviation of the values in mat"""



"""#### Get the sum of all the columns in mat"""



"""# Great Job!"""