# -*- coding: utf-8 -*-
"""Copy of Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POsnv8YB6_GR9p2CwUaIGW-FPsWtPux9

**NOTE: ALL THE COMMANDS FOR PLOTTING A FIGURE SHOULD ALL GO IN THE SAME CELL. SEPARATING THEM OUT INTO MULTIPLE CELLS MAY CAUSE NOTHING TO SHOW UP.**

# Exercises

Follow the instructions to recreate the plots using this data:

## Data
"""

import numpy as np
x = np.arange(0,100)
y = x*2
z = x**2

"""**Import matplotlib.pyplot as plt and set %matplotlib inline if you are using the jupyter notebook. What command do you use if you aren't using the jupyter notebook?**"""

import matplotlib.pyplot as plt

"""## Exercise 1

**Follow along with these steps**
* Create a figure object called fig using plt.figure()
* Use add_axes to add an axis to the figure canvas at [0,0,1,1]. Call this new axis ax.
* Plot (x,y) on that axes and set the labels and titles to match the plot below:
"""

fig=plt.figure()
ax=fig.add_axes([0,0,1,1])
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.plot(x,y)
ax.set_title("title")

"""## Exercise 2
**Create a figure object and put two axes on it, ax1 and ax2. Located at [0,0,1,1] and [0.2,0.5,.2,.2] respectively.**
"""

fig=plt.figure()
ax1=fig.add_axes([0,0,1,1])
ax2=fig.add_axes([0.2,0.5,.2,.2])

"""**Now plot (x,y) on both axes. And call your figure object to show it.**"""

ax1.plot(x,y)
ax2.plot(x,y)
plt.show()

"""## Exercise 3

**Create the plot below by adding two axes to a figure object at [0,0,1,1] and [0.2,0.5,.4,.4]**
"""

fig=plt.figure()
ax1=fig.add_axes([0,0,1,1])
ax2=fig.add_axes([0.2,0.5,0.4,.4])

"""**Now use x,y, and z arrays to recreate the plot below. Notice the xlimits and y limits on the inserted plot:**"""

ax1.plot(x,z)
ax2.plot(x,y)
ax2.set_xlim(20,22)
ax2.set_ylim(30,50)
ax2.set_title("zoom")

"""## Exercise 4

**Use plt.subplots(nrows=1, ncols=2) to create the plot below.**
"""

plt.subplots(nrows=1,ncols=2)

"""**Now plot (x,y) and (x,z) on the axes. Play around with the linewidth and style**"""

plt.subplot(1,2,1)
plt.plot(x,y,ls='--',color='b')
plt.subplot(1,2,2)
plt.plot(x,z,ls='-',color='r')

"""**See if you can resize the plot by adding the figsize() argument in plt.subplots() are copying and pasting your previous code.**"""

fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10, 5))
axes[0].plot(x,y,ls='--',color='blue')
axes[1].plot(x,z,ls='-',color='red')

"""# Great Job!"""